#!/bin/bash


echo "Se deben pasar tres argumentos cómo mínimo"
echo -e "1. La línea inicial, 2. La línea final y 3. El archivo a copiar"

echo ""

if [ $# -ge 3 ]; then
	if [[ -f $3 ]]; then
		sed -n "$1,$2p" $3 | xclip -selection clipboard
	else
		echo "No se ha podido detectar o encontrar el archivo. Operación cancelada."
	fi
else
	echo "Menos de tres parametros fueron pasados. Operación cancelada."
fi

# se recomienda que se cree un alias para este script, cpff como alias de copyFromFile
