#!/bin/bash

echo ""

if [ $# -ge 3 ]; then
	# validations:

	# is the 1st and 2nd args nums?
	if ! [[ $1 =~ ^[0-9]+$ ]] || ! [[ $2 =~ ^[0-9]+$ ]]; then
        	echo "The starting and ending lines must be numeric values. Operation canceled."
        	exit 1
    	fi

	# is the 3rd arg a file?
	if [[ -f $3 ]]; then
		sed -n "$1,$2p" $3 | xclip -selection clipboard
		echo "Content copied from line $1 to $2 of $3."
	else
		echo "The file could not be detected or found. Operation canceled."
	fi
fi

if [[ $# -ge 1 && $# -lt 3 ]]; then
	echo "Help:"
	echo "Usage: copyFromFile <start_line> <end_line> <file>"
   	echo "Copies lines from <start_line> to <end_line> in <file> to the clipboard."
	echo ""
	echo "You need to use three arguments"
	echo ""
    	exit 1
fi


if [[ $# -eq 0 || $1 == "--help" ]]; then
	echo "Help:"
	echo "Usage: copyFromFile <start_line> <end_line> <file>"
   	echo "Copies lines from <start_line> to <end_line> in <file> to the clipboard."
    	exit 0
fi

if ! command -v xclip &> /dev/null; then
    echo "xclip is not installed. Please install it first."
    exit 1
fi


echo ""

# It is recommended to create an alias for this script, such as 'cpff'.
